---
  - name: Provision Software
    remote_user: root
    hosts: all
    tasks:
      - name: Add git ppa
        tags: packages
        when: ansible_distribution == "Ubuntu"
        apt_repository:
          repo: 'ppa:git-core/ppa'
          state: present

      - name: Disable apt autoupdates
        tags: remote
        when: ansible_distribution == "Ubuntu"
        copy:
          content: |
             APT::Periodic::Update-Package-Lists "0";
             APT::Periodic::Unattended-Upgrade "0";

          dest: /etc/apt/apt.conf.d/20auto-upgrades

      - name: Disable apt-daily.timer
        tags: remote
        ansible.builtin.systemd:
          name: apt-daily.timer
          state: stopped
          enabled: false

      - name: Disable apt-daily service
        tags: remote
        ansible.builtin.systemd:
          name: apt-daily.service
          state: stopped
          enabled: false

      - name: Install essential distro packages (Ubuntu)
        apt:
          name: "{{ packages }}"
          update_cache: yes
          force_apt_get: yes
        tags: packages
        when: ansible_distribution == "Ubuntu"
        vars:
          packages:
            - git
            - gitg
            - gitk
            - git-doc
            - git-gui
            - git-email
            - tig
            - emacs
            - vim
            - micro
            - curl
            - python3-psutil  # for ansible

      - name: Install distro packages (Ubuntu)
        apt:
          name: "{{ packages }}"
          update_cache: yes
          force_apt_get: yes
        tags: packages2
        when: ansible_distribution == "Ubuntu"
        vars:
          packages:
            - gcc
            - g++
            - make
            - autoconf
            - automake
            - libtool
            - flex
            - bison
            - gdb
            - gcc-doc
            - gimp
            - inkscape
            - geeqie
            - graphviz
            - graphviz-doc
            - liblz4-tool
            - firefox
            - kcachegrind
            - gnome-builder
            - gedit
            - gedit-plugins
            - htop
            - curl
            - ncdu
            - moreutils
            - cython3
            - debian-archive-keyring
            - gpg
            - hwloc
            - screen
            - python-is-python3
            - python3-pip
            - python3-numpy
            - python3-scipy
            - python3-zmq
            - python3-yaml
            - python3-pytest
            - python3-colorama
            - python3-networkx
            - jupyter-client
            - jupyter-console
            - jupyter-notebook
            - jupyter-nbconvert
            - jupyter-qtconsole
            - python3-ipython
            - ipython3
            - python3-dask
            - python3-graphviz
            - python3-mpltoolkits.basemap
            - python3-distributed
            - python3-nose
            - python3-coverage
            - python3-line-profiler
            - python3-memory-profiler
            - python3-bcolz
            - python3-plotly
            - python3-opencv
            - python3-toolz
            - python3-joblib
            - python3-sklearn
            - python3-sklearn-pandas
            - python3-scipy
            - python3-matplotlib
            - python3-matplotlib-venn
            - python3-willow
            - python3-pyflakes
            - python3-sphinx
            - python3-sphinx-rtd-theme
            - python3-pytest
            - python3-pytest-pep8
            - python3-pytest-pylint
            - python3-pytest-cov
            - python3-mpi4py
            - python3-imageio
            - python3-h5py
            - python3-skimage
            - python3-tweepy
            - python3-xlrd
            - python3-seaborn
            - python3-venv
            - cufflinks
            - runsnakerun
            - libopenblas-base
            - libopenblas-dev
            - flite
            # - bloscpack

            # For pelita testing
            - xauth

            # In case gnome is weird, the tweak tool may help in adjusting hidden settings
            - gnome-tweak-tool

            # Optional timers for the status bar (can be helpful for pair-programming)
            - gnome-shell-pomodoro
            - gnome-shell-timer
 
      - name: Remove updater packages (Ubuntu)
        apt:
          name: "{{ packages }}"
          update_cache: yes
          force_apt_get: yes
          state: absent
        tags: packages
        when: ansible_distribution == "Ubuntu"
        vars:
          packages:
            - update-notifier
            - update-ma

      - name: Install distro packages (Fedora)
        dnf:
          name: "{{ packages }}"
        tags: packages
        when: ansible_distribution == "Fedora"
        vars:
          packages:
            - gcc
            - g++
            - make
            - autoconf
            - automake
            - libtool
            - flex
            - bison
            - gdb
            # - gcc-doc
            - gimp
            - inkscape
            - geeqie
            - graphviz
            - graphviz-doc
            - lz4
            - firefox
            - git
            - gitg
            - gitk
            - git-core-doc
            - git-gui
            - git-email
            - tig
            - kcachegrind
            - emacs
            - vim
            - gnome-builder
            - gedit
            - gedit-plugins
            - htop
            - curl
            - ncdu
            - moreutils
            - micro
            - curl
            - python3-Cython
            - gnupg2
            - hwloc
            - screen
            - python3-numpy
            - python3-scipy
            - python3-blosc
            - python3-zmq
            - python3-yaml
            - python3-colorama
            - python3-networkx
            - python3-jupyter-client
            - python3-jupyter-console
            - python3-jupyter-c-kernel
            - python3-jupyter-sphinx
            - python3-ipython
            - python3-pytest
            - python3-dask
            - python3-dask+array
            - python3-dask+bag
            - python3-dask+dataframe
            - python3-dask+delayed
            - python3-graphviz
            # - python3-mpltoolkits.basemap
            - python3-nose
            - python3-coverage
            # - python3-line-profiler
            # - python3-memory-profiler
            # - python3-bcolz
            - python3-plotly
            - python3-opencv
            - python3-toolz
            - python3-joblib
            - python3-scikit-learn
            - python3-scipy
            - python3-matplotlib
            # - python3-matplotlib-venn
            # - python3-willow
            - python3-pyflakes
            - python3-sphinx
            - python3-sphinx_rtd_theme
            - python3-pytest
            - python3-pytest-flake8
            - python3-pytest-flakes
            - python3-pytest-mpi
            - python3-pytest-cov
            - python3-mpi4py-mpich
            - python3-mpi4py-openmpi
            - python3-imageio
            - python3-h5py
            - python3-scikit-image
            # - python3-tweepy
            - python3-xlrd
            - python3-seaborn
            - python3-psutil
            # - cufflinks
            # - runsnakerun
            # - libopenblas-base: we probably want to pull in all blas implementations
            #                     and provide instructions how to switch using flexiblas.
            - flexiblas-devel
            - flite
            # - bloscpack

            # Installed using pip in Ubuntu
            - python3-pandas
            - python3-bokeh
            - python3-pysnooper

            # For pelita testing
            - xauth

            # For dconf ansible module
            - dbus-tools

      - name: Allow password authentication (Fedora)
        when: ansible_distribution == "Fedora"
        copy:
          content: |
             PasswordAuthentication yes

          dest: /etc/ssh/sshd_config.d/80-password-auth.conf

      - name: Allow X forwarding (Fedora)
        when: ansible_distribution == "Fedora"
        copy:
          content: |
             ForwardX11 yes

          dest: /etc/ssh/ssh_config.d/80-x-forwarding.conf

      - name: Reload sshd config
        ansible.builtin.systemd:
          name: sshd.service
          state: reloaded

      - name: Install latest git
        tags: packages
        when: ansible_distribution == "Ubuntu"
        apt:
          name: git
          state: latest
          force_apt_get: yes

      - name: Install desktop
        tags: packages2
        when: ansible_distribution == "Ubuntu"
        apt:
          name: ubuntu-desktop
          # Doesn't work with ansible 2.7 in Ubuntu 19.04
          # policy_rc_d: 101
          force_apt_get: yes

      - stat:
          path: /usr/bin/atom
        tags: packages
        register: atom_exists
      - name: Install atom
        tags: packages
        when: not atom_exists.stat.exists and ansible_distribution == "Ubuntu"
        apt:
          # deb: https://atom.io/download/deb
          deb: http://10.5.7.35:8000/deb
          force_apt_get: yes
        ignore_errors: yes

      - stat:
          path: /usr/bin/code
        tags: packages
        register: code_exists
      - name: Install visualstudio
        tags: packages2
        when: not code_exists.stat.exists and ansible_distribution == "Ubuntu"
        apt:
          deb: https://go.microsoft.com/fwlink/?LinkID=760868
          force_apt_get: yes

      - name: Set up autologin
        when: ansible_distribution == "Ubuntu"
        copy:
          src: files/custom.conf
          dest: /etc/gdm3/
        tags: remote

      - name: Set up autologin
        when: ansible_distribution == "Fedora"
        copy:
          src: files/custom.conf
          dest: /etc/gdm/
        tags: remote

      - name: Setup /etc/firefox/sysprefs.js
        copy:
          src: files/sysprefs.js
          dest: /etc/firefox/
        tags: remote

      - name: Set timezone to Europe/Rome
        timezone:
          name: Europe/Rome
        tags: remote

      - name: Set language to English
        copy:
          content: |
            LANG=en_US.UTF-8
          dest: /etc/locale.conf
        tags: remote

      - name: Set language to English
        copy:
          content: |
            LANG=en_US.UTF-8
          dest: /etc/default/locale
        tags: remote
        when: ansible_distribution == "Ubuntu"
