---
  - name: User setup
    remote_user: root
    become_user: student
    become: yes
    hosts: all
    tasks:
      - name: Install pip packages (Ubuntu)
        tags: user-packages
        when: ansible_distribution == "Ubuntu"
        pip:
          executable: pip3
          state: latest
          name:
            - pandas >= 0.25
            - pysnooper
            - bokeh
            - ipython_memwatcher
            - pyprof2calltree
            - git+https://github.com/ASPP/prof3to2.git
            - numba
            - meson >= 0.59
            - joblib
            - dask-jobqueue
            - pudb
            - altair
            - ipyparallel
            - snakeviz
            - vega_datasets
            - vega
            - pelita==2.2.0

      - name: Install pip packages (Fedora)
        tags: user-packages
        when: ansible_distribution == "Fedora"
        pip:
          executable: pip3
          state: latest
          name:
            - ipython_memwatcher
            - pyprof2calltree
            - git+https://github.com/ASPP/prof3to2.git
            - line-profiler
            - numba
            - altair
            - snakeviz
            - vega_datasets
            - vega
            - pelita==2.2.0

      # - name: Install Rike's vim config, if no other config is present
      #   command:
      #     cmd: git clone 'https://github.com/Debilski/vim-basic.git' '/home/student/.vim' && ln -s /home/student/.vim/vimrc /home/student/.vimrc && vim vim +PlugInstall +qall
      #     creates: /home/student/.vim
      #   tags: remote

      - name: Set up git
        tags: remote
        copy:
          content: |
            [core]
                editor = micro
            [user]
                name = ASPP Student
                email = student@localhost
            [init]
                defaultBranch = main

          dest: /home/student/.gitconfig

      - name: Disable screensaver
        tags: remote
        command: gsettings set org.gnome.desktop.session idle-delay 0
      - name: Disable screen lock
        tags: remote
        command: gsettings set org.gnome.desktop.lockdown disable-lock-screen true

      - name: Make ~/.local/bin/ directory
        file:
          dest: '/home/student/.local/bin/'
          state: directory
        tags: remote

      - name: Make python python3
        file:
          src: '/usr/bin/{{ item.src }}'
          dest: '/home/student/.local/bin/{{ item.dest }}'
          state: link
        when: ansible_distribution == "Ubuntu"
        with_items:
          - { src: pdb3,       dest: pdb }
          - { src: pydoc3,     dest: pydoc }
          - { src: pygettext3, dest: pygettext }
          - { src: pip3,       dest: pip }
          - { src: pytest-3,   dest: pytest }
          - { src: ipython3,   dest: ipython }
          - { src: cython3,    dest: cython }
        tags: user-packages

      - name: Install .bashrc (Ubuntu)
        when: ansible_distribution == "Ubuntu"
        copy:
          src: 'files/.bashrc'
          dest: '/home/student/.bashrc'
        tags: remote

      - name: Install .bashrc.d/
        copy:
          src: 'files/bashrc.d/'
          dest: '/home/student/.bashrc.d/'
        tags: remote

      - name: Create directory .config/micro
        file:
          path: /home/student/.config/micro/
          state: directory
        tags: remote
      - name: Install .config/micro/settings.json
        copy:
          src: 'files/micro-settings.json'
          dest: '/home/student/.config/micro/settings.json'
        tags: remote
      - name: Install .config/micro/bindings.json
        copy:
          src: 'files/micro-bindings.json'
          dest: '/home/student/.config/micro/bindings.json'
        tags: remote

      - name: Remove .bash_history
        file:
          path: '/home/student/.bash_history'
          state: absent
        tags: cleanup

      - name: Remove .ipynb_checkpoints/
        file:
          path: '/home/student/.ipynb_checkpoints/'
          state: absent
        tags: cleanup

      - name: Set input keyboards to us/es/de
        dconf:
          key: /org/gnome/desktop/input-sources/sources
          value: "[('xkb', 'us'), ('xkb', 'latam')]"
          state: present
        tags: remote

      - name: Disable lock screen
        dconf:
          key: /org/gnome/desktop/lockdown/disable-lock-screen
          value: "true"
          state: present
        tags: remote

      - name: Setup favourites
        dconf:
          key: /org/gnome/shell/favorite-apps
          value: "['firefox.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Nautilus.desktop', 'code.desktop', 'libreoffice-writer.desktop']"
          state: present
        tags: remote

      - name: Create ~/Desktop
        ansible.builtin.file:
          path: '/home/student/Desktop'
          state: directory
          mode: '0755'
        tags: remote

      - name: Copy background
        copy:
          src: 'files/aspp_latam.jpg'
          dest: '/home/student/Desktop/wallpaper.jpg'
        tags: remote

      - name: Activate background
        tags: remote
        command: gsettings set org.gnome.desktop.background picture-uri '"file:///home/student/Desktop/wallpaper.jpg"'

      - name: Add github to /home/student/.ssh/known_hosts
        tags: remote
        ansible.builtin.known_hosts:
          path: /home/student/.ssh/known_hosts
          name: github.com
          key: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          state: present

