#!/bin/bash

[ "$1" = "final" ] || exit 0

# sed -r 's/(options.*) rw/\1 ro systemd.mask=systemd-repart.service systemd.mask=systemd-remount-fs.service systemd.unit=multi-user.target/; s/(title.*)Fedora.*/\1 Text boot (installer)/' </efi/loader/entries/* >/efi/loader/entries/installer.conf

mkosi-chroot git clone https://github.com/ASPP/installation /root/installation
mkosi-chroot ansible-playbook -i localhost, --connection local /root/installation/setup-ansible.yml
